package logging

import "text/template"

var Header = template.Must(template.New("logging_header").Parse(`
//	Code generated by protoc-gen-httpclient. DO NOT EDIT.
//	versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.0

package {{ .Registry.PackageName }}

import (
	"context"
	"time"

	"github.com/go-kit/log"
)

type loggingMiddleware struct {
	logger log.Logger

	next {{ .Registry.ServiceName }}Server

	Unimplemented{{ .Registry.ServiceName }}Server
}

func LoggingMiddleware(logger log.Logger) func({{ .Registry.ServiceName }}Server) {{ .Registry.ServiceName }}Server {
	return func(next {{ .Registry.ServiceName }}Server) {{ .Registry.ServiceName }}Server {
		return &loggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}
`))
