package server

import "text/template"

var Header = template.Must(template.New("logging_header").Parse(`
//	Code generated by protoc-gen-httpclient. DO NOT EDIT.
//	versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.0

package {{ .Registry.PackageName }}

import (
	{{ .Modules }}
)

type HTTPClientParams struct {
	URL *url.URL

	AllowUndeclaredFields bool
}

type httpClient struct {
	reqURL string

	client *http.Client

	unmarshaler *jsonpb.Unmarshaler

	Unimplemented{{ .Registry.ServiceName }}Server
}

func NewHTTPClient(params *HTTPClientParams) {{ .Registry.ServiceName }}Server {

	return &httpClient{
		reqURL: params.URL.String(),

		client: &http.Client{},

		unmarshaler: &jsonpb.Unmarshaler{
			AllowUnknownFields: params.AllowUndeclaredFields,
			AnyResolver:        nil,
		},
	}
}
`))
